---
name: ublue-os-cosmic
description: My custom ublue os image based on https://github.com/ublue-os/cosmic/

base-image: ghcr.io/ublue-os/cosmic-silverblue
image-version: 41-amd64

modules:
  - type: signing
  # - from-file: common_modules/akmods.yaml
  # - from-file: common_modules/bling.yaml
  - from-file: common_modules/brew.yaml
  # - from-file: common_modules/chezmoi.yaml
  # - from-file: common_modules/containerfile.yaml
  # - from-file: common_modules/copy.yaml
  # - from-file: common_modules/default-flatpacks.yaml
  # - from-file: common_modules/files.yaml
  - from-file: common_modules/fonts.yaml
  # - from-file: common_modules/gnome-extensions.yaml
  # - from-file: common_modules/gschema-overrides.yaml
  # - from-file: common_modules/initramfs.yaml
  # - from-file: common_modules/justfiles.yaml
  - from-file: common_modules/rpm-ostree.yaml
  # - from-file: common_modules/systemd.yaml
  # - from-file: common_modules/yafti.yaml
